### ISSUE TITLE
RSRHelper 1.0.0 affects FileVault Wallpaper on Ventura

### ISSUE THREAD

**Issue by mrdc** [khronokernel/RSRHelper#1]
Hello, 

`RSRHelper 1.0.0` completely removes a wallpaper in FileVault on Ventura: there is only black background.
Disabling RSRHelper fixes the issue.

```
iMac11,1
macOS 13.6
RSRHelper 1.0.0
```

**Comment by khronokernel** [comment]
FileVault is UEFI-based, while RSRHelper is Kernel based. The kext can't even loaded at time of FileVault, as macOS' kernel isn't even loaded due to needing drive decryption.

**Comment by mrdc** [comment]
> FileVault is UEFI-based, while RSRHelper is Kernel based.

Yes, I understand, but RSRHelper somehow affects FV wallpaper for me. I've tested 10 times with 100% reproduction.
Turning it off fixes the issue, I can boot 10 times and wallpaper is fine, turning on RSRHelper and always black screen in FileVault.

**Comment by mrdc** [comment]
> The kext can't even loaded at time of FileVault, as macOS' kernel isn't even loaded

I understand, but the kext is loaded when macOS is started and macOS can do something with preboot partition and caches for EFI, which RSRHelper can affect somehow, because it deals with RSR updates under the hood.

**Comment by mrdc** [comment]
Strange, I've enabled RSRHelper and now FV wallpaper is OK. Maybe it's somehow related to have RSRHelper enabled during macOS installation, so something is not properly updated at preboot volume. Will try to investigate further.
